
CREATE TABLE IF NOT EXISTS PRODUCT
(SKU VARCHAR(200) NOT NULL, NAME VARCHAR(200) NOT NULL, PRICE FLOAT NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL, PRIMARY KEY (SKU));

CREATE TABLE IF NOT EXISTS ORDERS
(ID int auto_increment NOT NULL, EMAIL VARCHAR(200) NOT NULL, CREATED_ON TIMESTAMP NOT NULL, PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS ORDERS_TO_PRODUCTS
(PRODUCT VARCHAR(200) NOT NULL, ORDERS int NOT NULL, PRICE FLOAT NOT NULL, PRIMARY KEY (PRODUCT, ORDERS));